### ISSUE TITLE
kb.KbError in README example

### ISSUE THREAD

**Issue by slowrunner** [severin-lemaignan/pykb#2]
(Sorry to be forcing a look at old code; I really want to give my robot an RDF/OWL KB.)

When I ran the code in the (pykb==2.0) README against the new minimalKB 1.0, the kb issues an error:
```
2021-02-25 08:44:48,543: Searching ['?obj', '?agent'] in models {'default'} matching:
	- ('?agent', 'desires', '?obj')
	- ('?obj', 'rdf:type', 'Action')
2021-02-25 08:44:48,547: request failed: Only a single variable in queries can be currently requested.
2021-02-25 08:44:48,580: Closing connection to client.
Traceback (most recent call last):
  File "./test_pykb.py", line 58, in <module>
    for action_lover in kb["?agent desires ?obj", "?obj rdf:type Action"]:
  File "/usr/local/lib/python3.7/dist-packages/kb.py", line 316, in __getitem__
    return self.find(list(allvars), ["%s %s %s"%p for p in patterns], None, models)
  File "/usr/local/lib/python3.7/dist-packages/kb.py", line 143, in innermethod
    return self._client.call_server(m, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/kb.py", line 526, in call_server
    raise KbError(value)
kb.KbError: 'kberror: Only a single variable in queries can be currently requested.'
```

```
#!/usr/bin/env python3


"""
	FILE: test_pykb.py
	From: https://github.com/severin-lemaignan/pykb/blob/master/README.md
	REQUIREMENTS:
		sudo pip3 install minimalkb
		sudo pip3 install pykb
	USAGE:
		minimalkb &
		./test_pykb.py
		pgrep -a minimalkb
		kill xxxx
"""

import kb
import time

REASONING_DELAY = 0.2

def onevent(evt):
    print("Something happened! %s" % evt)

with kb.KB() as kb:

    kb += ["alfred rdf:type Human", "alfred likes icecream"]

    if 'alfred' in kb:
        print("Hello Alfred!")

    if 'alfred likes icecream' in kb:
        print("Oh, you like icrecreams?")

    kb -= ["alfred likes icecream"]

    if 'alfred likes *' not in kb:
        print("You don't like anything? what a pity...")

    kb += ["Human rdfs:subClassOf Animal"]
    time.sleep(REASONING_DELAY) # give some time to the reasoner

    if 'alfred rdf:type Animal' in kb:
        print("I knew it!")

    for facts in kb.about("Human"):
        print(facts)

    for known_human in kb["?human rdt:type Human"]:
        print(known_human)


    kb += ["alfred desires jump", "alfred desires oil"]
    kb += ["jump rdf:type Action"]

    for action_lover in kb["?agent desires ?obj", "?obj rdf:type Action"]:
        print(action_lover)

    kb.subscribe(["?agent isIn ?loc", "?loc rdf:type Room"], onevent)
    kb += ["alfred isIn sleepingroom", "sleepingroom rdf:type Room"]

    time.sleep(1) # event should have been triggered!
```

**Comment by severin-lemaignan** [comment]
Thanks for reporting! Not really a bug in `pykb`: the error only tells you that you are trying to execute a request that can not be answered by the (limited) reasoning capabilities of `minimalkb`. However, if you use `pykb` with another knowledge base (like ORO), this error would not happen.

Updating the example to clarify the behaviour.
